name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make build || go build ./...

      - name: Run tests
        run: make test || go test -v ./...

      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          golangci-lint run
